name: try-reflex-test

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Nix
        uses: cachix/install-nix-action@v12
      - name: try-reflex
        run: nix-build -A tryReflexShell --substituters https://nixcache.reflex-frp.org --trusted-public-keys ryantrinkle.com-1:JJiAKaRv9mWgpVAz8dwewnZe0AzzEAzPkagE9SP5NWI=
